apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: amf
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: openverso/open5gs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
